import React, { useContext } from "react";

import Head from "next/head";
import Search from "../components/Search";
import CTA from "../components/CTA";
import Logo from "../components/Logo";
import Content from "../components/Content";
import Conversation from "../components/Conversation";
import { DialogContext } from "../providers/DialogProvider";
import SelectMenu from "../components/SelectMenu";

export default function Home() {
  const { conversation } = useContext(DialogContext);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center min-h-screen">
        <div className="w-full md:w-[50rem] lg:w-[65rem] flex flex-col gap-7 px-4 md:px-20 mt-4">
          <Logo />
          <CTA />
          {conversation && conversation.length > 0 ? (
            <Conversation />
          ) : (
            <Content />
          )}
        </div>
        <footer className="sticky top-[100vh] flex gap-2 justify-center w-full md:w-[50rem] lg:w-[65rem] pb-4 pt-2 px-4 md:px-20">
          <Search />
          <SelectMenu />
        </footer>
      </main>
    </div>
  );
}
